remote_theme: minimal-mistakes-jekyll
title: A Student's Guide to Climate Activism


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
